# Generated by Django 2.2.28 on 2023-04-10 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id_process',
        ),
        migrations.AddField(
            model_name='player',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Process'),
        ),
        migrations.AlterField(
            model_name='process',
            name='levels_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Level'),
        ),
    ]
