# Generated by Django 2.2.28 on 2023-04-10 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230410_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Grupo'),
        ),
    ]
