# Generated by Django 2.2.28 on 2023-04-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230410_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='id_grupo',
            field=models.PositiveIntegerField(),
        ),
    ]
