# Generated by Django 2.2.28 on 2023-04-10 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230410_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='process',
        ),
        migrations.RemoveField(
            model_name='process',
            name='levels_data',
        ),
        migrations.AddField(
            model_name='level',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Process'),
        ),
        migrations.AddField(
            model_name='process',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
    ]
