# Generated by Django 2.2.28 on 2023-04-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230410_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='times_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nametag',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id_grupo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
