# Generated by Django 2.2.28 on 2023-04-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230412_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='num_level',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
