# Generated by Django 2.2.28 on 2023-04-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230412_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='time',
            new_name='time_l1',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='total_mistakes',
            new_name='total_mistakes_l2',
        ),
        migrations.RemoveField(
            model_name='record',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='record',
            name='num_level',
        ),
        migrations.AddField(
            model_name='record',
            name='complete_l1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='complete_l2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='complete_l3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='time_l2',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='time_l3',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='total_mistakes_l1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='total_mistakes_l3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
