# Generated by Django 2.2.28 on 2023-04-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230412_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='complete_l1',
            field=models.BooleanField(blank=True, null=True, verbose_name='Complete Level 1'),
        ),
        migrations.AlterField(
            model_name='record',
            name='complete_l2',
            field=models.BooleanField(blank=True, null=True, verbose_name='Complete Level 2'),
        ),
        migrations.AlterField(
            model_name='record',
            name='complete_l3',
            field=models.BooleanField(blank=True, null=True, verbose_name='Complete Level 3'),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_l1',
            field=models.DurationField(blank=True, null=True, verbose_name='Time Level 1'),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_l2',
            field=models.DurationField(blank=True, null=True, verbose_name='Time Level 2'),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_l3',
            field=models.DurationField(blank=True, null=True, verbose_name='Time Level 3'),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_mistakes_l1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mistakes Level 1'),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_mistakes_l2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mistakes Level 2'),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_mistakes_l3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mistakes Level 3'),
        ),
    ]
