# Generated by Django 2.2.28 on 2023-04-16 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230413_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_level', models.PositiveIntegerField(blank=True, null=True, verbose_name='Level')),
                ('max_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Score')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=50, null=True)),
                ('enter_at', models.DateTimeField(blank=True, null=True, verbose_name='Ingreso')),
                ('exit_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('level_enter', models.PositiveIntegerField(blank=True, null=True, verbose_name='Level Start')),
                ('level_exit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Level End')),
            ],
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='id_grupo',
            new_name='grupo_id',
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='no_lista',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de lista'),
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='session',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Session'),
        ),
    ]
