# Generated by Django 2.2.28 on 2023-04-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_player_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
