# Generated by Django 2.2.28 on 2023-04-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20230419_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='level_exit',
        ),
        migrations.AddField(
            model_name='session',
            name='max_level1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='max_level2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='max_level3',
            field=models.IntegerField(default=0),
        ),
    ]
