# Generated by Django 2.2.28 on 2023-04-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20230419_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='level_enter',
            field=models.PositiveIntegerField(default=1, verbose_name='Level Start'),
        ),
    ]
