# Generated by Django 2.2.28 on 2023-04-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='max_level1',
        ),
        migrations.RemoveField(
            model_name='session',
            name='max_level2',
        ),
        migrations.RemoveField(
            model_name='session',
            name='max_level3',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='grupo',
        ),
        migrations.AddField(
            model_name='grupo',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Teacher'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Level')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Session')),
            ],
        ),
    ]
