# Generated by Django 2.2.28 on 2023-04-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20230426_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='history',
        ),
        migrations.AddField(
            model_name='session',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
    ]
