# Generated by Django 2.2.28 on 2023-04-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20230427_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='num_session',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
