# Generated by Django 2.2.28 on 2023-05-02 15:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20230427_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Teacher', unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='num_level',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='session',
            name='enter_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Ingreso'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='correo_escolar',
            field=models.EmailField(default='profesor@example.com', max_length=50, unique=True, verbose_name='Correo Escolar'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=50, unique=True, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Usuario'),
        ),
    ]
