# Generated by Django 4.2.4 on 2023-08-31 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_actividad_administrador_entrega_progreso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='file',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='entrega_id',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='tokens_assigned',
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='actividad_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='progress_id',
        ),
        migrations.AddField(
            model_name='actividad',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.entrega', unique=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tokens',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='administrador',
            name='progreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.progreso', unique=True),
        ),
        migrations.AddField(
            model_name='progreso',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.actividad', unique=True),
        ),
        migrations.AddField(
            model_name='progreso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.usuario', unique=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='correo',
            field=models.EmailField(default='admin@example.com', max_length=50, unique=True, verbose_name='Correo Admin'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='password',
            field=models.CharField(max_length=50, unique=True, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=50, unique=True, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Usuario'),
        ),
    ]
