# Generated by Django 4.2.4 on 2023-08-31 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_entrega_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='file_name',
        ),
    ]
