# Generated by Django 4.2.4 on 2023-09-26 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0007_pregunta_remove_actividad_tokens_entrega_filename_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autodiagnostico",
            name="pregunta",
        ),
        migrations.AddField(
            model_name="pregunta",
            name="autodiagnostico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.autodiagnostico",
                unique=True,
            ),
        ),
    ]
