# Generated by Django 4.2.4 on 2023-09-26 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0009_alter_pregunta_titulo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pregunta",
            old_name="titulo",
            new_name="pregunta",
        ),
    ]
