# Generated by Django 4.2.4 on 2023-09-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_autodiagnostico_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No_binario', 'No binario'), ('Sin_especificar', 'Prefiero no decir')], default='Sin_especificar', max_length=25, verbose_name='Género'),
        ),
    ]
