# Generated by Django 4.2.4 on 2023-09-30 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0013_alter_usuario_genero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name="actividad",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="autodiagnostico",
            name="index",
        ),
        migrations.AddField(
            model_name="autodiagnostico",
            name="respuesta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.respuesta",
                unique=True,
            ),
        ),
    ]
