# Generated by Django 4.2.4 on 2023-09-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0013_alter_usuario_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="genero",
            field=models.CharField(
                choices=[
                    ("Sin_especificar", "Prefiero no decir"),
                    ("Masculino", "Masculino"),
                    ("Femenino", "Femenino"),
                    ("No_binario", "No binario"),
                    ("Otro", "Otro"),
                ],
                default="Sin_especificar",
                max_length=25,
                verbose_name="Género",
            ),
        ),
    ]
