# Generated by Django 4.2.6 on 2023-10-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_respuesta_remove_actividad_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='TipoPregunta'),
        ),
    ]
