# Generated by Django 4.2.4 on 2023-10-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0015_pregunta_tipo_pregunta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregunta",
            name="tipo_pregunta",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                unique=True,
                verbose_name="Tipo Pregunta",
            ),
        ),
        migrations.AlterField(
            model_name="respuesta",
            name="respuesta",
            field=models.PositiveIntegerField(default=1, verbose_name="Respuesta"),
        ),
    ]
