# Generated by Django 4.2.4 on 2023-10-03 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0016_alter_pregunta_tipo_pregunta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Institución",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="País",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="disciplina",
            field=models.CharField(
                choices=[
                    ("Ingeniería y Ciencias", "Ingeniería y Ciencias"),
                    ("Humanidades y Educación", "Humanidades y Educación"),
                    ("Ciencias Sociales", "Ciencias Sociales"),
                    ("Ciencias de la Salud", "Ciencias de la Salud"),
                    ("Arquitectura, Arte y Diseño", "Arquitectura, Arte y Diseño"),
                    ("Negocios", "Negocios"),
                ],
                default="Ingeniería y Ciencias",
                max_length=60,
                verbose_name="Disciplina de Interés",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="grado",
            field=models.CharField(
                choices=[
                    (
                        "Pregrado",
                        "Pregrado(licenciatura, profesional, universidad, grado)",
                    ),
                    ("Posgrado", "Posgrado(maestría, doctorado)"),
                    ("Educación continua", "Educación continua"),
                ],
                default="Pregrado",
                max_length=60,
                verbose_name="Grado de Estudiso",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="genero",
            field=models.CharField(
                choices=[
                    ("Sin_especificar", "Prefiero no decir"),
                    ("Masculino", "Masculino"),
                    ("Femenino", "Femenino"),
                    ("No_binario", "No binario"),
                ],
                default="Sin_especificar",
                max_length=50,
                verbose_name="Género",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.institucion",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.pais",
                unique=True,
            ),
        ),
    ]
