# Generated by Django 4.2.4 on 2023-10-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0017_institucion_pais_usuario_disciplina_usuario_grado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregunta",
            name="tipo_pregunta",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Tipo Pregunta"
            ),
        ),
    ]
