# Generated by Django 4.2.4 on 2023-10-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_autodiagnostico_pregunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='progreso',
        ),
    ]
