# Generated by Django 4.2.4 on 2023-10-08 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_remove_actividad_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pais',
        ),
    ]
