# Generated by Django 4.2.6 on 2023-10-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_institucion_nombre_alter_usuario_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contraseña'),
        ),
    ]
