# Generated by Django 4.2.4 on 2023-10-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_usuario_institucion_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='institucion',
        ),
    ]
