# Generated by Django 4.2.4 on 2023-10-09 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_usuario_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.pais', unique=True),
        ),
    ]
