# Generated by Django 4.2.6 on 2023-10-09 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_progreso_actividad_alter_usuario_institucion_and_more'),
        ('app1', '0024_alter_usuario_password'),
        ('app1', '0026_usuario_pais'),
    ]

    operations = [
    ]
