# Generated by Django 4.2.4 on 2023-10-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_merge_20231009_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodiagnostico',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
