# Generated by Django 4.2.6 on 2023-10-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_merge_20231009_0331'),
        ('app1', '0028_autodiagnostico_completada'),
    ]

    operations = [
    ]
