# Generated by Django 4.2.6 on 2023-10-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_merge_20231009_0547'),
        ('app1', '0030_remove_progreso_entrega_progreso_file_and_more'),
    ]

    operations = [
    ]
