# Generated by Django 4.2.6 on 2023-10-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0031_merge_20231009_0756"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progreso",
            name="file",
            field=models.FileField(default="", upload_to="archivos/"),
        ),
    ]
