# Generated by Django 4.2.4 on 2023-10-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0032_alter_progreso_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrador",
            name="correo",
            field=models.EmailField(max_length=50, unique=True, verbose_name="Correo"),
        ),
        migrations.AlterField(
            model_name="administrador",
            name="password",
            field=models.CharField(max_length=50, verbose_name="Contraseña"),
        ),
    ]
